services:
  app:
    build: .
    restart: always
    container_name: playit-tasks-backend
    ports:
      - "8001:8001"
    networks:
      - skynet
    volumes:
      - uploads:/uploads
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

networks:
  skynet:
    external: true

volumes:
  uploads: